# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'access_levels_table.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1175, 528)
        self.tabWidget_2 = QtWidgets.QTabWidget(Dialog)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 1561, 481))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableW_access_levels = QtWidgets.QTableWidget(self.tab)
        self.tableW_access_levels.setGeometry(QtCore.QRect(420, 20, 391, 171))
        self.tableW_access_levels.setRowCount(0)
        self.tableW_access_levels.setColumnCount(6)
        self.tableW_access_levels.setObjectName("tableW_access_levels")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 20, 321, 171))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 10, 91, 151))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_25.setEnabled(True)
        self.label_25.setScaledContents(False)
        self.label_25.setWordWrap(False)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_16.setEnabled(True)
        self.label_16.setScaledContents(False)
        self.label_16.setWordWrap(False)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setEnabled(True)
        self.label_19.setScaledContents(False)
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_4.setGeometry(QtCore.QRect(180, 10, 131, 151))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_name_access_levels = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_name_access_levels.sizePolicy().hasHeightForWidth())
        self.text_name_access_levels.setSizePolicy(sizePolicy)
        self.text_name_access_levels.setMaximumSize(QtCore.QSize(110, 16777215))
        self.text_name_access_levels.setText("")
        self.text_name_access_levels.setFrame(True)
        self.text_name_access_levels.setReadOnly(False)
        self.text_name_access_levels.setObjectName("text_name_access_levels")
        self.verticalLayout_3.addWidget(self.text_name_access_levels)
        self.text_discrp_access_levels = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_discrp_access_levels.sizePolicy().hasHeightForWidth())
        self.text_discrp_access_levels.setSizePolicy(sizePolicy)
        self.text_discrp_access_levels.setMaximumSize(QtCore.QSize(110, 16777215))
        self.text_discrp_access_levels.setText("")
        self.text_discrp_access_levels.setFrame(True)
        self.text_discrp_access_levels.setReadOnly(False)
        self.text_discrp_access_levels.setObjectName("text_discrp_access_levels")
        self.verticalLayout_3.addWidget(self.text_discrp_access_levels)
        self.text_access_levels_note = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_access_levels_note.sizePolicy().hasHeightForWidth())
        self.text_access_levels_note.setSizePolicy(sizePolicy)
        self.text_access_levels_note.setMaximumSize(QtCore.QSize(110, 16777215))
        self.text_access_levels_note.setText("")
        self.text_access_levels_note.setFrame(True)
        self.text_access_levels_note.setReadOnly(False)
        self.text_access_levels_note.setObjectName("text_access_levels_note")
        self.verticalLayout_3.addWidget(self.text_access_levels_note)
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 811, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_access_levels_add = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_access_levels_add.setObjectName("pushButton_access_levels_add")
        self.horizontalLayout.addWidget(self.pushButton_access_levels_add)
        self.pushButton_access_levels_del = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_access_levels_del.setObjectName("pushButton_access_levels_del")
        self.horizontalLayout.addWidget(self.pushButton_access_levels_del)
        self.pushButton_access_levels_change = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_access_levels_change.setObjectName("pushButton_access_levels_change")
        self.horizontalLayout.addWidget(self.pushButton_access_levels_change)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.tableW_access_table = QtWidgets.QTableWidget(self.tab_20)
        self.tableW_access_table.setGeometry(QtCore.QRect(350, 40, 601, 291))
        self.tableW_access_table.setRowCount(0)
        self.tableW_access_table.setColumnCount(6)
        self.tableW_access_table.setObjectName("tableW_access_table")
        self.layoutWidget_59 = QtWidgets.QWidget(self.tab_20)
        self.layoutWidget_59.setGeometry(QtCore.QRect(70, 380, 811, 41))
        self.layoutWidget_59.setObjectName("layoutWidget_59")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_59)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_access_table_add = QtWidgets.QPushButton(self.layoutWidget_59)
        self.pushButton_access_table_add.setObjectName("pushButton_access_table_add")
        self.horizontalLayout_19.addWidget(self.pushButton_access_table_add)
        self.pushButton_access_table_del = QtWidgets.QPushButton(self.layoutWidget_59)
        self.pushButton_access_table_del.setObjectName("pushButton_access_table_del")
        self.horizontalLayout_19.addWidget(self.pushButton_access_table_del)
        self.pushButton_access_table_change = QtWidgets.QPushButton(self.layoutWidget_59)
        self.pushButton_access_table_change.setObjectName("pushButton_access_table_change")
        self.horizontalLayout_19.addWidget(self.pushButton_access_table_change)
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_20)
        self.groupBox_26.setGeometry(QtCore.QRect(10, 10, 321, 361))
        self.groupBox_26.setTitle("")
        self.groupBox_26.setObjectName("groupBox_26")
        self.layoutWidget_60 = QtWidgets.QWidget(self.groupBox_26)
        self.layoutWidget_60.setGeometry(QtCore.QRect(50, 10, 98, 331))
        self.layoutWidget_60.setObjectName("layoutWidget_60")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.layoutWidget_60)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_74 = QtWidgets.QLabel(self.layoutWidget_60)
        self.label_74.setEnabled(True)
        self.label_74.setScaledContents(False)
        self.label_74.setWordWrap(False)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_42.addWidget(self.label_74)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget_60)
        self.label_75.setEnabled(True)
        self.label_75.setScaledContents(False)
        self.label_75.setWordWrap(False)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_42.addWidget(self.label_75)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_60)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_42.addWidget(self.label_11)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget_60)
        self.label_76.setEnabled(True)
        self.label_76.setScaledContents(False)
        self.label_76.setWordWrap(False)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_42.addWidget(self.label_76)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_60)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_42.addWidget(self.label_13)
        self.layoutWidget_61 = QtWidgets.QWidget(self.groupBox_26)
        self.layoutWidget_61.setGeometry(QtCore.QRect(180, 10, 131, 331))
        self.layoutWidget_61.setObjectName("layoutWidget_61")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.layoutWidget_61)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.text_name_table = QtWidgets.QLineEdit(self.layoutWidget_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_name_table.sizePolicy().hasHeightForWidth())
        self.text_name_table.setSizePolicy(sizePolicy)
        self.text_name_table.setMaximumSize(QtCore.QSize(110, 16777215))
        self.text_name_table.setText("")
        self.text_name_table.setFrame(True)
        self.text_name_table.setReadOnly(False)
        self.text_name_table.setObjectName("text_name_table")
        self.verticalLayout_43.addWidget(self.text_name_table)
        self.comboBox_id_access_levels = QtWidgets.QComboBox(self.layoutWidget_61)
        self.comboBox_id_access_levels.setObjectName("comboBox_id_access_levels")
        self.verticalLayout_43.addWidget(self.comboBox_id_access_levels)
        self.comboBox_id_users_groups = QtWidgets.QComboBox(self.layoutWidget_61)
        self.comboBox_id_users_groups.setObjectName("comboBox_id_users_groups")
        self.verticalLayout_43.addWidget(self.comboBox_id_users_groups)
        self.text_discrp = QtWidgets.QLineEdit(self.layoutWidget_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_discrp.sizePolicy().hasHeightForWidth())
        self.text_discrp.setSizePolicy(sizePolicy)
        self.text_discrp.setMaximumSize(QtCore.QSize(110, 16777215))
        self.text_discrp.setText("")
        self.text_discrp.setFrame(True)
        self.text_discrp.setReadOnly(False)
        self.text_discrp.setObjectName("text_discrp")
        self.verticalLayout_43.addWidget(self.text_discrp)
        self.text_note = QtWidgets.QLineEdit(self.layoutWidget_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_note.sizePolicy().hasHeightForWidth())
        self.text_note.setSizePolicy(sizePolicy)
        self.text_note.setMaximumSize(QtCore.QSize(110, 16777215))
        self.text_note.setText("")
        self.text_note.setFrame(True)
        self.text_note.setReadOnly(False)
        self.text_note.setObjectName("text_note")
        self.verticalLayout_43.addWidget(self.text_note)
        self.tabWidget_2.addTab(self.tab_20, "")

        self.retranslateUi(Dialog)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_25.setText(_translate("Dialog", "name"))
        self.label_16.setText(_translate("Dialog", "discrp"))
        self.label_19.setText(_translate("Dialog", "note"))
        self.pushButton_access_levels_add.setText(_translate("Dialog", "Добавить"))
        self.pushButton_access_levels_del.setText(_translate("Dialog", "PushButton"))
        self.pushButton_access_levels_change.setText(_translate("Dialog", "PushButton"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Dialog", "access_levels"))
        self.pushButton_access_table_add.setText(_translate("Dialog", "Добавить"))
        self.pushButton_access_table_del.setText(_translate("Dialog", "Удалить"))
        self.pushButton_access_table_change.setText(_translate("Dialog", "Изменить"))
        self.label_74.setText(_translate("Dialog", "name_table"))
        self.label_75.setText(_translate("Dialog", "id_access_level"))
        self.label_11.setText(_translate("Dialog", "id_users_group"))
        self.label_76.setText(_translate("Dialog", "discrp"))
        self.label_13.setText(_translate("Dialog", "note"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_20), _translate("Dialog", "access_table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

